sudo: false 
language: node_js 
cache: 
  directories:
    - node_modules 
node_js: 6 
branches:
  only:
    - master 
notifications: 
  email: false 
script:
  -  gulp 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: GITHUB_TOKEN 
  on:
    branch: master       
